# Generated by Django 5.2.10 on 2026-01-25 07:48

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('total_contacts', models.IntegerField(default=0)),
                ('total_groups', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNSUBSCRIBED', 'Unsubscribed'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Primary Marketing Phone', max_length=100)),
                ('session_name', models.CharField(help_text='Internal WAHA session ID', max_length=100, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('load_percentage', models.IntegerField(default=25, help_text='Percentage of traffic to route here (0-100)')),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('PAUSED', 'Paused')], default='DISCONNECTED', max_length=20)),
                ('total_sent', models.IntegerField(default=0)),
                ('sent_today', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_between_messages_min', models.IntegerField(default=1, help_text='Min seconds delay')),
                ('delay_between_messages_max', models.IntegerField(default=10, help_text='Max seconds delay')),
                ('warmup_mode', models.BooleanField(default=False)),
                ('pause_every_x_messages', models.IntegerField(default=5, help_text='Pulse size')),
                ('pause_duration_seconds', models.IntegerField(default=30, help_text='Rest duration')),
                ('max_messages_per_hour', models.IntegerField(default=0, help_text='0 = Unlimited')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, help_text='If sent to a group', max_length=100, null=True)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('phone_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phoneinstance')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.property')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='properties',
            field=models.ManyToManyField(related_name='campaigns', to='core.property'),
        ),
    ]
