# Generated by Django 5.2.10 on 2026-01-30 05:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_property_bedrooms_remove_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsettings',
            name='delay_between_messages_max',
            field=models.IntegerField(default=12, help_text='Max seconds delay'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='delay_between_messages_min',
            field=models.IntegerField(default=8, help_text='Min seconds delay'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, default=list, size=None),
        ),
    ]
