# Generated by Django 5.2.10 on 2026-01-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_campaignsettings_delay_between_messages_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
    ]
