# Generated by Django 5.2.10 on 2026-01-30 07:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='delay_between_messages_max',
            field=models.IntegerField(default=10, help_text='Max seconds delay'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='delay_between_messages_min',
            field=models.IntegerField(default=1, help_text='Min seconds delay'),
        ),
    ]
