# Generated by Django 5.2.10 on 2026-01-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
    ]
