# Generated by Django 5.2.10 on 2026-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_property_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsettings',
            name='delay_between_messages_max',
            field=models.IntegerField(default=12, help_text='Max seconds delay'),
        ),
        migrations.AlterField(
            model_name='campaignsettings',
            name='delay_between_messages_min',
            field=models.IntegerField(default=8, help_text='Min seconds delay'),
        ),
    ]
