# Generated by Django 5.2.10 on 2026-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_campaignsettings_delay_between_messages_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='post_to_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='post_to_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_to_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
