# Generated by Django 5.2.10 on 2026-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campaign_post_to_facebook_campaign_post_to_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='platform',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], default='WHATSAPP', max_length=20),
        ),
    ]
