# Generated by Django 5.2.10 on 2026-01-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messagelog_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinstance',
            name='api_url',
            field=models.CharField(default='http://waha:3000', help_text='WAHA API URL (e.g. http://waha:3000)', max_length=255),
        ),
    ]
