# Generated by Django 5.2.10 on 2026-01-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_phoneinstance_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinstance',
            name='session_name',
            field=models.CharField(help_text='Internal WAHA session ID (default for WAHA Core)', max_length=100),
        ),
    ]
