# Generated by Django 5.2.10 on 2026-01-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_phoneinstance_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_to_all_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('participants_count', models.IntegerField(default=0)),
                ('phone_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.phoneinstance')),
            ],
            options={
                'unique_together': {('phone_instance', 'group_id')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.whatsappgroup'),
        ),
    ]
