# Generated by Django 5.2.10 on 2026-01-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_campaign_send_to_all_groups_whatsappgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='group_id',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.whatsappgroup'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='waha_group_id',
            field=models.CharField(blank=True, help_text='Legacy/Dual store', max_length=100, null=True),
        ),
    ]
