# Generated by Django 5.2.11 on 2026-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_messagelog_group_id_messagelog_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_to_all_contacts',
            field=models.BooleanField(default=True),
        ),
    ]
