# Generated by Django 5.2.11 on 2026-02-17 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_campaign_send_to_all_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(related_name='collections', to='core.whatsappgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
