# Generated by Django 5.2.11 on 2026-02-17 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_groupcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcollection',
            name='groups',
        ),
        migrations.AddField(
            model_name='groupcollection',
            name='group_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of WhatsApp Group JIDs (e.g. 12345@g.us)', size=None),
        ),
    ]
